# Generated by Django 3.2.9 on 2022-03-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://neptunestatic.s3.ap-southeast-1.amazonaws.com/profile/default.png', upload_to='profile'),
        ),
    ]
