# Generated by Django 3.2.9 on 2022-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateproductmodel',
            name='product_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
