# Generated by Django 3.2.9 on 2022-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_updateproductmodel_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateproductmodel',
            name='product_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='updateproductmodel',
            name='product_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
